# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate processes.
#'
#' @return A matrix with rows; 1 = log of long rate, 2 = difference (long - short), 3 = log of long rate volatility
#'
#' @export
#'
generate_processes <- function(N, short_rate = 0.0263, long_rate = 0.0287, beta_i = 0.00509, beta_alpha = 0.02685, beta_nu = 0.04001, tau_i = 0.0350, tau_alpha = 0.01, tau_nu = 0.0287, sigma_i = 0.0287, sigma_alpha = 0.04148, sigma_nu = 0.11489, phi = 0.0002, psi = 0.25164, theta = 1.0) {
    .Call('_AIRG_generate_processes', PACKAGE = 'AIRG', N, short_rate, long_rate, beta_i, beta_alpha, beta_nu, tau_i, tau_alpha, tau_nu, sigma_i, sigma_alpha, sigma_nu, phi, psi, theta)
}

#' Generate rates based on processes
#' 
#' @return A 2xn matrix with rows: 1 = short rate, 2 = long rate.
#'
#' @export
#'
generate_rates <- function(N) {
    .Call('_AIRG_generate_rates', PACKAGE = 'AIRG', N)
}

